import { normalizeLabel } from "./labels";

/**
 * A plain-English line for every word the classifier knows.
 *
 * Solo hands out words from the model's own 345 labels, which means it will
 * cheerfully ask somebody to draw an anvil, a goatee or asparagus. Knowing the
 * word is not the game — drawing it is — so a word nobody recognises is just a
 * dead round.
 *
 * Every label has a line here, deliberately: a partial map would fail on
 * exactly the obscure words that need it. They are short, plain and describe
 * the thing rather than define it, because what a player needs is something to
 * draw, not a dictionary entry.
 *
 * Written here rather than fetched: this is the same feature that promises to
 * work offline and send nothing anywhere.
 */
const HINTS: Record<string, string> = {
  "aircraft carrier": "a huge ship planes take off from",
  "airplane": "a machine with wings that flies",
  "alarm clock": "a clock that wakes you up",
  "ambulance": "a van that rushes sick people to hospital",
  "angel": "a person with wings and a halo",
  "animal migration": "animals travelling together in a line",
  "ant": "a tiny insect that lives in a nest",
  "anvil": "a heavy iron block a blacksmith hits on",
  "apple": "a round fruit with a little stem",
  "arm": "your shoulder down to your hand",
  "asparagus": "long thin green stalks you eat",
  "axe": "a blade on a handle for chopping wood",
  "backpack": "a bag you wear on your back",
  "banana": "a long yellow fruit you peel",
  "bandage": "a strip of cloth over a cut",
  "barn": "a big farm building for animals",
  "baseball": "a small white ball with stitching",
  "baseball bat": "a long wooden club for hitting a ball",
  "basket": "a woven container with a handle",
  "basketball": "a large ball you bounce and throw in a hoop",
  "bat": "a small animal with wings that flies at night",
  "bathtub": "a big tub you sit in to wash",
  "beach": "sand, sea and maybe a sun",
  "bear": "a big furry animal with round ears",
  "beard": "hair on a man's chin",
  "bed": "where you sleep, with a pillow",
  "bee": "a small striped insect that makes honey",
  "belt": "a strap around your waist with a buckle",
  "bench": "a long seat for two or more people",
  "bicycle": "two wheels, pedals and handlebars",
  "binoculars": "two tubes you look through to see far",
  "bird": "a small animal with wings and a beak",
  "birthday cake": "a cake with candles on top",
  "blackberry": "a small dark berry made of bumps",
  "blueberry": "a tiny round blue fruit",
  "book": "pages between two covers",
  "boomerang": "a bent stick that flies back to you",
  "bottlecap": "the little metal lid off a bottle",
  "bowtie": "a small bow worn at the neck",
  "bracelet": "a band worn around your wrist",
  "brain": "the wrinkly organ inside your head",
  "bread": "a baked loaf you slice",
  "bridge": "a road that crosses over water",
  "broccoli": "a green vegetable shaped like a little tree",
  "broom": "a long handle with bristles for sweeping",
  "bucket": "a round container with a handle",
  "bulldozer": "a digger with a big front blade",
  "bus": "a long vehicle with many windows and seats",
  "bush": "a small round leafy plant",
  "butterfly": "an insect with big patterned wings",
  "cactus": "a spiky desert plant with arms",
  "cake": "a round sweet thing you slice at parties",
  "calculator": "a small box of number buttons",
  "calendar": "a grid of days on a page",
  "camel": "a desert animal with humps on its back",
  "camera": "a box with a lens for taking photos",
  "camouflage": "a blotchy pattern that hides things",
  "campfire": "logs with flames on top",
  "candle": "a wax stick with a flame",
  "cannon": "a big tube on wheels that shoots balls",
  "canoe": "a narrow boat you paddle",
  "car": "four wheels, windows and a body",
  "carrot": "a long orange vegetable with leafy top",
  "castle": "a stone building with towers",
  "cat": "a small pet with pointed ears and whiskers",
  "ceiling fan": "blades that spin on the ceiling",
  "cello": "a big violin you play sitting down",
  "cell phone": "a small screen you hold in your hand",
  "chair": "a seat with a back and four legs",
  "chandelier": "a fancy hanging light with many bulbs",
  "church": "a building with a steeple and cross",
  "circle": "a perfectly round ring",
  "clarinet": "a long black tube you blow into",
  "clock": "a round face with two hands",
  "cloud": "a fluffy shape in the sky",
  "coffee cup": "a paper cup with a lid",
  "compass": "a dial with a needle pointing north",
  "computer": "a screen with a keyboard",
  "cookie": "a round biscuit with chocolate bits",
  "cooler": "a box that keeps drinks cold",
  "couch": "a long soft seat for several people",
  "cow": "a farm animal with patches and udders",
  "crab": "a flat shell with claws and legs",
  "crayon": "a coloured wax stick for drawing",
  "crocodile": "a long reptile with a toothy snout",
  "crown": "a gold hat with points, worn by a king",
  "cruise ship": "a huge passenger ship with many decks",
  "cup": "a small container you drink from",
  "diamond": "a sparkling gem with flat cut sides",
  "dishwasher": "a machine that washes plates",
  "diving board": "a springy plank over a pool",
  "dog": "a pet with a wagging tail",
  "dolphin": "a smooth sea animal with a fin",
  "donut": "a ring of cake with icing",
  "door": "a rectangle with a handle",
  "dragon": "a big lizard with wings that breathes fire",
  "dresser": "a chest of drawers",
  "drill": "a tool that spins to make holes",
  "drums": "round drums you hit with sticks",
  "duck": "a water bird with a flat bill",
  "dumbbell": "a bar with weights at both ends",
  "ear": "the curl on the side of your head",
  "elbow": "the bend in the middle of your arm",
  "elephant": "a huge grey animal with a trunk",
  "envelope": "a paper pocket for a letter",
  "eraser": "a small rubber block that rubs out pencil",
  "eye": "an oval with a circle inside",
  "eyeglasses": "two lenses joined over your nose",
  "face": "eyes, a nose and a mouth",
  "fan": "blades that spin to make a breeze",
  "feather": "a light quill from a bird",
  "fence": "posts and rails around a field",
  "finger": "one digit on your hand",
  "fire hydrant": "a short red post firefighters use",
  "fireplace": "a fire in an opening in a wall",
  "firetruck": "a red truck with a ladder",
  "fish": "a body with fins and a tail",
  "flamingo": "a tall pink bird standing on one leg",
  "flashlight": "a tube that shines a beam of light",
  "flip flops": "flat sandals with a toe strap",
  "floor lamp": "a tall stand with a lampshade",
  "flower": "petals around a middle, on a stem",
  "flying saucer": "a round spaceship with a dome",
  "foot": "the bottom of your leg, with toes",
  "fork": "a handle with prongs for eating",
  "frog": "a green hopper with long back legs",
  "frying pan": "a shallow pan with a long handle",
  "garden": "flowers and plants in neat rows",
  "garden hose": "a long coiled tube for watering",
  "giraffe": "a spotted animal with a very long neck",
  "goatee": "a small beard on the chin only",
  "golf club": "a long stick with a bent head",
  "grapes": "a bunch of small round fruits",
  "grass": "lots of thin green blades",
  "guitar": "a body with a long neck and strings",
  "hamburger": "a patty in a round bun",
  "hammer": "a handle with a heavy head for nails",
  "hand": "a palm with five fingers",
  "harp": "a tall triangle frame with many strings",
  "hat": "something you wear on your head",
  "headphones": "two cups joined over your head",
  "hedgehog": "a small animal covered in spines",
  "helicopter": "a flying machine with spinning blades on top",
  "helmet": "a hard hat that protects your head",
  "hexagon": "a shape with six straight sides",
  "hockey puck": "a flat black disc you hit on ice",
  "hockey stick": "a long stick with a bent blade",
  "horse": "a large animal with a mane you ride",
  "hospital": "a building with a cross for sick people",
  "hot air balloon": "a big balloon with a basket under it",
  "hot dog": "a sausage in a long bun",
  "hot tub": "a warm bubbling pool for sitting in",
  "hourglass": "two glass bulbs with sand running through",
  "house": "a box with a roof and a door",
  "house plant": "a plant in a pot indoors",
  "hurricane": "a huge swirl of storm clouds",
  "ice cream": "scoops on top of a pointed cone",
  "jacket": "a coat with sleeves and a zip",
  "jail": "a room with bars on the window",
  "kangaroo": "a hopper with a pouch and big tail",
  "key": "a small metal shape that opens a lock",
  "keyboard": "rows of letter keys you type on",
  "knee": "the bend in the middle of your leg",
  "knife": "a blade with a handle for cutting",
  "ladder": "two rails with rungs for climbing",
  "lantern": "a light in a case with a handle",
  "laptop": "a screen and keyboard that fold together",
  "leaf": "a flat green shape from a tree",
  "leg": "your hip down to your foot",
  "light bulb": "a glass bulb that glows",
  "lighter": "a small box that makes a flame",
  "lighthouse": "a tall tower with a light for ships",
  "lightning": "a jagged bolt from the sky",
  "line": "one straight stroke",
  "lion": "a big cat with a shaggy mane",
  "lipstick": "a colour stick for lips, in a tube",
  "lobster": "a sea creature with big front claws",
  "lollipop": "a round sweet on a stick",
  "mailbox": "a box on a post for letters",
  "map": "a drawing of roads and places",
  "marker": "a thick pen for bold lines",
  "matches": "small sticks that light a flame",
  "megaphone": "a cone you shout through",
  "mermaid": "half a person, half a fish",
  "microphone": "a round head on a stand for singing",
  "microwave": "a box that heats food fast",
  "monkey": "a climbing animal with a long tail",
  "moon": "a crescent or circle in the night sky",
  "mosquito": "a tiny insect that bites you",
  "motorbike": "two wheels with an engine",
  "mountain": "a tall pointed peak",
  "mouse": "a small animal with a long thin tail",
  "moustache": "hair above the lip",
  "mouth": "lips, and maybe teeth",
  "mug": "a cup with a handle",
  "mushroom": "a round cap on a short stalk",
  "nail": "a thin metal pin with a flat head",
  "necklace": "a chain worn around the neck",
  "nose": "the bit in the middle of your face",
  "ocean": "waves stretching to the horizon",
  "octagon": "a shape with eight straight sides",
  "octopus": "a round head with eight arms",
  "onion": "a round vegetable with papery layers",
  "oven": "a box with a door for baking",
  "owl": "a bird with huge round eyes",
  "paintbrush": "a handle with bristles for painting",
  "paint can": "a tin of paint with a handle",
  "palm tree": "a tall trunk with leaves on top",
  "panda": "a black and white bear",
  "pants": "trousers, with two legs",
  "paper clip": "a bent wire that holds pages",
  "parachute": "a dome of cloth with strings",
  "parrot": "a colourful bird with a curved beak",
  "passport": "a small booklet for travelling",
  "peanut": "a bumpy shell with nuts inside",
  "pear": "a fruit narrow at the top, round below",
  "peas": "small green balls in a pod",
  "pencil": "a wooden stick with a sharp point",
  "penguin": "a black and white bird that cannot fly",
  "piano": "black and white keys in a row",
  "pickup truck": "a car with an open back tray",
  "picture frame": "a border around a picture",
  "pig": "a round pink farm animal with a snout",
  "pillow": "a soft rectangle for your head",
  "pineapple": "a spiky fruit with leaves on top",
  "pizza": "a flat round slice with toppings",
  "pliers": "a gripping tool with two handles",
  "police car": "a car with a light on the roof",
  "pond": "a small pool of water with reeds",
  "pool": "a rectangle of water for swimming",
  "popsicle": "frozen juice on a stick",
  "postcard": "a card with a picture and a stamp",
  "potato": "a lumpy brown vegetable",
  "power outlet": "a wall socket with holes",
  "purse": "a small bag with a handle",
  "rabbit": "a small animal with long ears",
  "raccoon": "a furry animal with a mask and stripy tail",
  "radio": "a box with a dial and speaker",
  "rain": "drops falling from a cloud",
  "rainbow": "an arch of coloured bands",
  "rake": "a long handle with teeth for leaves",
  "remote control": "a slim box covered in buttons",
  "rhinoceros": "a heavy animal with a horn on its nose",
  "rifle": "a long gun held at the shoulder",
  "river": "water winding between banks",
  "roller coaster": "a track with steep loops and hills",
  "rollerskates": "boots with wheels underneath",
  "sailboat": "a boat with a sail",
  "sandwich": "filling between two slices of bread",
  "saw": "a blade with jagged teeth",
  "saxophone": "a curved brass horn you blow",
  "school bus": "a long yellow bus for children",
  "scissors": "two blades joined, with finger holes",
  "scorpion": "claws, legs and a curled stinger tail",
  "screwdriver": "a handle with a thin shaft for screws",
  "sea turtle": "a swimming turtle with flippers",
  "see saw": "a plank balanced in the middle",
  "shark": "a big fish with a fin on its back",
  "sheep": "a woolly farm animal",
  "shoe": "something you wear on your foot",
  "shorts": "trousers that stop above the knee",
  "shovel": "a handle with a scoop for digging",
  "sink": "a basin with a tap",
  "skateboard": "a plank with four small wheels",
  "skull": "a bony head with empty eye holes",
  "skyscraper": "a very tall building with many windows",
  "sleeping bag": "a padded bag you sleep inside",
  "smiley face": "two dots and a curved smile",
  "snail": "a slow creature carrying a spiral shell",
  "snake": "a long wavy body with no legs",
  "snorkel": "a mask with a breathing tube",
  "snowflake": "a six-armed ice crystal",
  "snowman": "stacked snowballs with a carrot nose",
  "soccer ball": "a ball of black and white patches",
  "sock": "soft footwear worn inside a shoe",
  "speedboat": "a fast boat throwing up spray",
  "spider": "a small body with eight legs",
  "spoon": "a handle with a small bowl on the end",
  "spreadsheet": "a grid of boxes filled with numbers",
  "square": "four equal straight sides",
  "squiggle": "a wiggly scribbled line",
  "squirrel": "a small climber with a bushy tail",
  "stairs": "steps going up",
  "star": "a shape with five points",
  "steak": "a thick slice of meat",
  "stereo": "a music player with two speakers",
  "stethoscope": "tubes a doctor listens through",
  "stitches": "thread sewn across a cut",
  "stop sign": "a red eight-sided road sign",
  "stove": "a cooker with rings on top",
  "strawberry": "a red heart-shaped fruit with seeds",
  "streetlight": "a tall post with a lamp on top",
  "string bean": "a long thin green bean",
  "submarine": "a boat that travels under water",
  "suitcase": "a case with a handle for travelling",
  "sun": "a circle with rays around it",
  "swan": "a white bird with a long curved neck",
  "sweater": "a warm knitted top",
  "swing set": "a frame with swings hanging from it",
  "sword": "a long blade with a handguard",
  "syringe": "a tube with a needle for injections",
  "table": "a flat top on four legs",
  "teapot": "a pot with a spout and handle",
  "teddy-bear": "a soft toy bear",
  "telephone": "a handset on a base with a dial",
  "television": "a screen in a box",
  "tennis racquet": "an oval frame with strings and a handle",
  "tent": "a triangle of cloth you sleep in",
  "The Eiffel Tower": "a tall iron tower in Paris",
  "The Great Wall of China": "a long wall winding over hills",
  "The Mona Lisa": "a famous painting of a smiling woman",
  "tiger": "a big striped cat",
  "toaster": "a slot machine that browns bread",
  "toe": "one digit on your foot",
  "toilet": "a bowl with a seat and a tank",
  "tooth": "a white shape with roots",
  "toothbrush": "a handle with small bristles",
  "toothpaste": "a squeezy tube for cleaning teeth",
  "tornado": "a spinning funnel touching the ground",
  "tractor": "a farm vehicle with huge back wheels",
  "traffic light": "a box with red, amber and green lights",
  "train": "an engine pulling carriages",
  "tree": "a trunk with branches and leaves",
  "triangle": "three straight sides",
  "trombone": "a brass horn with a sliding tube",
  "truck": "a big vehicle for carrying loads",
  "trumpet": "a small brass horn with three buttons",
  "t-shirt": "a simple top with short sleeves",
  "umbrella": "a canopy on a handle for rain",
  "underwear": "what you wear under your clothes",
  "van": "a boxy vehicle for carrying things",
  "vase": "a tall container for flowers",
  "violin": "a small instrument played with a bow",
  "washing machine": "a box with a round door for clothes",
  "watermelon": "a big green fruit, red inside",
  "waterslide": "a curving slide into a pool",
  "whale": "a huge sea animal with a spout",
  "wheel": "a round rim with spokes",
  "windmill": "a tower with turning sails",
  "wine bottle": "a tall bottle with a narrow neck",
  "wine glass": "a bowl on a thin stem",
  "wristwatch": "a small clock on a strap",
  "yoga": "a person stretching in a pose",
  "zebra": "a striped horse",
  "zigzag": "a sharp line that turns back and forth",
};

/** Lower-cased and punctuation-free, so a lookup never misses on a hyphen. */
const BY_KEY = new Map(Object.entries(HINTS).map(([label, hint]) => [normalizeLabel(label), hint]));

/** The one-line description of a word, or null when there is nothing to add. */
export function hintFor(word: string | null | undefined): string | null {
  if (!word) return null;
  return BY_KEY.get(normalizeLabel(word)) ?? null;
}
