// GENERATED from src/lib/game/clueBank.ts by scripts/build-edge-function.mjs.
// Do not edit — change the original and run `npm run build:edge`.

export const CLUE_BANK: Record<string, string[]> = {

  cat: ["Purrs, naps, judges you silently", "Nine lives, zero obedience"],
  dog: ["Loyal, waggy, loves a thrown stick", "Best friend with a wet nose"],
  fish: ["Lives wet, breathes through gills", "Swims in a bowl or the sea"],
  bird: ["Feathered, sings at sunrise", "Builds a nest, lays eggs"],
  cow: ["Moos, chews grass all day", "Gives us milk on the farm"],
  pig: ["Pink, curly tail, loves mud", "Oinks in a sty"],
  duck: ["Quacks and paddles on a pond", "Webbed feet, waterproof feathers"],
  bee: ["Buzzes, makes honey, stripy", "Pollinates flowers, has a sting"],
  frog: ["Green hopper, catches flies", "Starts life as a tadpole"],
  owl: ["Hoots at night, big round eyes", "Wise night hunter in a tree"],
  bat: ["Sleeps upside down in a cave", "Flies at dusk, uses echoes"],
  crab: ["Walks sideways with pincers", "Hard shell, lives on the beach"],
  rabbit: ["Hops, long ears, loves carrots", "Lives in a burrow, twitchy nose"],
  monkey: ["Swings in trees, loves bananas", "Cheeky climber with a long tail"],
  turtle: ["Slow mover with a hard home", "Retreats into its shell"],
  penguin: ["Waddles on ice in a tuxedo", "Swims well, cannot fly"],
  giraffe: ["Tallest neck on the savannah", "Eats leaves from treetops"],
  octopus: ["Eight arms, squirts ink", "Clever sea creature, no bones"],
  squirrel: ["Bushy tail, buries nuts", "Darts up trees in the park"],
  dolphin: ["Clever swimmer, clicks and leaps", "Friendly grey sea mammal"],
  hedgehog: ["Spiky ball that snuffles at night", "Rolls up when frightened"],
  flamingo: ["Pink wader on one leg", "Stands in shallow water, curved beak"],
  chameleon: ["Changes colour to hide", "Swivel eyes, very long tongue"],
  rhinoceros: ["Armoured giant with a horn", "Heavy grey beast of the plains"],
  jellyfish: ["Wobbly, stings, drifts in the sea", "See-through blob with tentacles"],
  caterpillar: ["Munches leaves, becomes a butterfly", "Fuzzy crawler with many legs"],
  grasshopper: ["Chirps in summer fields", "Green springer with long back legs"],
  orangutan: ["Ginger ape of the rainforest", "Long arms, swings through branches"],
  porcupine: ["Walking pincushion", "Rattles its sharp quills"],

  apple: ["Keeps the doctor away", "Crunchy, red or green, grows on trees"],
  pizza: ["Cheesy slice from Italy", "Round, sliced into triangles"],
  cake: ["Candles on top, sung to", "Sweet bake for a birthday"],
  egg: ["Cracked for breakfast", "Comes in a shell from a hen"],
  corn: ["Yellow cob, pops when heated", "Grows tall in a field, eaten on the cob"],
  milk: ["White drink from a cow", "Poured on cereal"],
  taco: ["Folded shell, Mexican filling", "Crunchy street food you hold"],
  pear: ["Green fruit shaped like a bell", "Sweet, grainy, grows on a tree"],
  bread: ["Sliced loaf for toast", "Baked from flour and yeast"],
  soup: ["Hot liquid meal in a bowl", "Eaten with a spoon on a cold day"],
  banana: ["Yellow, peeled, monkeys love it", "Curved fruit in a bunch"],
  popcorn: ["Cinema snack that pops", "Kernels burst into fluffy white"],
  pancake: ["Flipped in a pan, served with syrup", "Flat breakfast stack"],
  cupcake: ["Small iced bake in paper", "Individual birthday treat"],
  burger: ["Patty in a bun with pickles", "Fast food you hold in two hands"],
  noodles: ["Slurped with chopsticks", "Long strands in broth"],
  sandwich: ["Filling between two slices", "Packed lunch classic"],
  pineapple: ["Spiky skin, sweet yellow inside", "Tropical fruit with a crown"],
  watermelon: ["Green outside, red and juicy inside", "Summer fruit full of black seeds"],
  spaghetti: ["Long strands with tomato sauce", "Twirled on a fork, Italian"],
  strawberry: ["Red, seedy outside, with cream", "Sweet summer berry, heart shaped"],
  marshmallow: ["Toasted on a campfire stick", "Squishy white sugar pillow"],
  gingerbread: ["Spiced biscuit shaped like a person", "Festive house made of biscuit"],
  cheeseburger: ["Patty plus a melted yellow slice", "Fast food with dairy on top"],

  ball: ["Round, bouncy, kicked or thrown", "Used in most sports"],
  book: ["Pages you turn and read", "Sits on a shelf, has chapters"],
  cup: ["Holds your morning drink", "Has a handle, sits on a saucer"],
  hat: ["Worn on your head", "Keeps sun off your face"],
  key: ["Opens a locked door", "Jangles in your pocket"],
  shoe: ["Worn on your foot, has laces", "Comes in pairs, protects toes"],
  kite: ["Flown on a windy day", "String, tail, soars in the sky"],
  drum: ["Hit with sticks, keeps the beat", "Loud, round, in a band"],
  bell: ["Rings to say school is over", "Clangs when you shake it"],
  sock: ["Worn inside a shoe", "Always one missing after washing"],
  spoon: ["Scoops your cereal", "Rounded cutlery for soup"],
  clock: ["Ticks and shows the hour", "Hands go round on a wall"],
  camera: ["Click, and the moment is saved", "Has a lens and a shutter"],
  guitar: ["Six strings, strummed", "Played at a campfire singalong"],
  pencil: ["Written with, rubbed out", "Wooden, sharpened, grey marks"],
  backpack: ["Carried on both shoulders", "Holds your books for school"],
  toothbrush: ["Used twice a day with paste", "Small bristles for your smile"],
  scissors: ["Two blades that cut paper", "Snip snip, kept away from toddlers"],
  umbrella: ["Opens when it pours", "Keeps you dry on a wet walk"],
  ladder: ["Rungs you climb to reach high", "Leaned against a wall"],
  balloon: ["Filled with air, pops with a bang", "Floats at a party"],
  bicycle: ["Two wheels and pedals", "Ride it with a helmet on"],
  telescope: ["Brings distant stars close", "Long tube for stargazing"],
  typewriter: ["Clacks, dings, no delete key", "Old machine for writing letters"],
  skateboard: ["Four wheels and a plank", "Ollie, kickflip, grind"],
  helicopter: ["Spinning blades, hovers in place", "Lands on a rooftop pad"],
  lighthouse: ["Warns ships off the rocks", "Tall tower with a sweeping beam"],
  wheelbarrow: ["One wheel, two handles, full of soil", "Pushed around the garden"],

  sun: ["Rises in the east, warms us", "The star we orbit"],
  moon: ["Glows at night, has phases", "Astronauts walked on it"],
  tree: ["Trunk, branches, leaves", "Gives shade and drops acorns"],
  star: ["Twinkles far away at night", "Wished upon, shines in the dark"],
  rain: ["Falls from grey clouds", "Brings out umbrellas"],
  leaf: ["Turns gold and falls in autumn", "Green, flat, grows on a branch"],
  rock: ["Hard lump you trip on", "Skimmed across a pond"],
  snow: ["White and cold, makes a man", "Falls in winter, builds drifts"],
  cloud: ["Fluffy and white in the sky", "Blocks the sunshine, carries rain"],
  fire: ["Warm, orange, crackles", "Put out with water"],
  rainbow: ["Seven colours after a shower", "Arc in the sky, pot of gold"],
  volcano: ["Erupts with molten rock", "Smoking mountain, lava flows"],
  island: ["Land with sea all around", "Castaway ends up here"],
  cactus: ["Spiky plant in the desert", "Stores water, hurts to hug"],
  mountain: ["Climbed with rope and boots", "Snowy peak, very tall"],
  river: ["Flows to the sea", "Crossed by a bridge"],
  sunflower: ["Tall, yellow, follows the light", "Big seedy face on a stalk"],
  iceberg: ["Mostly hidden underwater", "Frozen hazard that sank a liner"],
  waterfall: ["Cascades over a cliff edge", "Loud, wet, rainbow in the spray"],
  tornado: ["Spinning funnel of wind", "Carries houses away in Kansas"],
  constellation: ["Join the dots in the night sky", "Orion is a famous one"],
  avalanche: ["Snow thunders down a slope", "Skiers fear this white wall"],

  house: ["Four walls and a roof", "Where you sleep at night"],
  tent: ["Canvas shelter with pegs", "Packed up for a festival"],
  farm: ["Tractors, barns and animals", "Where crops are grown"],
  park: ["Green space with swings", "Walk the dog here"],
  boat: ["Floats, has oars or a sail", "Takes you across water"],
  train: ["Runs on rails, has carriages", "Leaves from a platform"],
  castle: ["Moat, turrets and a drawbridge", "Where a king once lived"],
  airport: ["Check in, then take off", "Runways, gates and luggage belts"],
  library: ["Quiet shelves, borrow and return", "Whisper here, books everywhere"],
  treehouse: ["Hideout up in the branches", "Rope ladder, no grown ups"],
  playground: ["Swings, slides and a roundabout", "Where break time happens"],
  windmill: ["Sails turn in the breeze", "Dutch landmark that grinds grain"],
  igloo: ["Dome built from frozen blocks", "Arctic shelter, surprisingly warm"],
  campsite: ["Pitch your tent here", "Fire, marshmallows, sleeping bags"],
  "amusement park": ["Roller coasters and candy floss", "Day out with rides and queues"],
  "space station": ["Orbiting home for astronauts", "Floating lab above the planet"],
  submarine: ["Travels deep below the waves", "Periscope up, dives underwater"],
  skyscraper: ["Hundreds of floors, needs a lift", "Scrapes the clouds downtown"],

  run: ["What you do to catch a bus", "Faster than walking, out of breath"],
  jump: ["Both feet leave the ground", "Over a puddle or onto a bed"],
  swim: ["Front crawl in a pool", "Move through water, no boat"],
  sleep: ["Eight hours with eyes closed", "Dreams happen during this"],
  dance: ["Move to the beat", "Ballet or disco, both count"],
  sing: ["Use your voice to make a tune", "Karaoke involves doing this"],
  juggling: ["Three balls in the air at once", "Circus skill, keep them moving"],
  surfing: ["Standing up on a wave", "Board, beach, wetsuit"],
  skiing: ["Down the slope on two planks", "Poles, goggles, fresh powder"],
  fishing: ["Rod, bait and a lot of waiting", "Hoping something bites the hook"],
  camping: ["A weekend in a tent", "Sleeping bags and a fire outdoors"],
  painting: ["Brush, palette and a canvas", "What Van Gogh did for a living"],
  skydiving: ["Leap from a plane with a chute", "Freefall, then a big canopy"],
  tightrope: ["Balancing high on a thin wire", "Circus walk with a long pole"],
  snorkelling: ["Mask, tube and a view of the reef", "Float face down, watch the fish"],
  gardening: ["Weeding, planting and watering", "Spade, gloves and muddy knees"],

  "cold feet": ["Nerves before the big day", "Almost backing out at the altar"],
  "big fish": ["Important person in a small pond", "The one worth catching"],
  "hot dog": ["Sausage in a bun with mustard", "Ballpark snack, also a show off"],
  "couch potato": ["Sofa dweller with a remote", "Watches telly all weekend"],
  "break the ice": ["First awkward words at a party", "Get a frosty group talking"],
  "spill the beans": ["Let the secret out", "Accidentally reveal the surprise"],
  "piece of cake": ["Easier than expected", "No trouble at all"],
  "cat nap": ["Forty winks in the afternoon", "Short doze on the sofa"],
  "night owl": ["Still awake at 2am", "Does their best work after dark"],
  "raining cats and dogs": ["Absolutely pouring outside", "Heaviest downpour imaginable"],
  "elephant in the room": ["The obvious thing nobody mentions", "Huge issue everyone ignores"],
  "burning the midnight oil": ["Working long past bedtime", "Still at the desk at 3am"],
  "bull in a china shop": ["Clumsy where care is needed", "Wrecks the delicate crockery"],
  "under the weather": ["Not feeling your best", "A bit poorly, off work"],

  love: ["Hearts, roses and February", "The strongest feeling of all"],
  time: ["Measured in hours, never enough", "Flies when you are having fun"],
  luck: ["Four leaf clovers bring it", "Chance going your way"],
  noise: ["The opposite of quiet", "Neighbours complain about it"],
  gravity: ["Keeps your feet on the ground", "Newton and a falling apple"],
  memory: ["What a photograph preserves", "Fades with age, jogged by a smell"],
  silence: ["Golden, they say", "Total absence of sound"],
  jealousy: ["The green eyed monster", "Wanting what someone else has"],
  deadline: ["The date it must be finished by", "Looms, then whooshes past"],
  nostalgia: ["Missing how things used to be", "Warm feeling about the old days"],
  karma: ["What goes around comes around", "The universe settling the score"],
  procrastination: ["Doing anything but the task", "Tidying instead of working"],
  "existential crisis": ["Questioning the point of it all", "Three in the morning, big questions"],
  "imposter syndrome": ["Feeling like a fraud at work", "Sure you will be found out"],
  inflation: ["Prices rising year on year", "Your money buying less"],
  bureaucracy: ["Forms, stamps and three queues", "Red tape everywhere"],
  "midlife crisis": ["Forty, and suddenly a sports car", "Big changes in your late forties"],

  selfie: ["Photo of yourself, arm outstretched", "Front camera, duck face optional"],
  podcast: ["Episodes in your headphones", "Two people chatting on a schedule"],
  emoji: ["Tiny picture in a message", "Smiley face you tap to send"],
  meme: ["Picture with a joke caption", "Spreads across the internet fast"],
  "time machine": ["Device for visiting the past", "Doc Brown built one in a car"],
  "rock band": ["Guitar, bass, drums and a singer", "Plays loud gigs in leather"],
  superhero: ["Cape, mask and a secret identity", "Saves the city before teatime"],
  "zombie movie": ["Shuffling undead on screen", "Film where survivors barricade doors"],
  "road trip": ["Long drive with a playlist", "Petrol stations and motels"],
  karaoke: ["Singing to lyrics on a screen", "Brave performance in a bar"],
  "mad scientist": ["Wild hair and a bubbling lab", "Cackles at his own experiment"],
  "conspiracy theory": ["Pinboard with red string", "Belief that it was all staged"],
  "parallel universe": ["Another reality alongside ours", "Everything the same but different"],
  "escape room": ["Locked in, solving puzzles", "One hour to find the clues and leave"],
  "haunted mansion": ["Creaky old place full of ghosts", "Spooky house on the hill"],

  coffee: ["Brown, bitter, needed at 7am", "Beans ground for a morning cup"],
  traffic: ["Bumper to bumper on the motorway", "Why you were late this morning"],
  laundry: ["Basket of washing to fold", "Machine, powder, then the line"],
  "group chat": ["Forty unread messages from friends", "Everyone typing at once"],
  "open floor plan": ["Office with no walls or doors", "Everyone hears everyone"],
  "flat tyre": ["Pull over and get the spare", "Hissing sound then a wobbly ride"],
  "jury duty": ["Summoned to judge a case", "A letter you cannot ignore"],
  "spring cleaning": ["Top to bottom once a year", "Windows, cupboards, everything"],
  "office small talk": ["Chatting about the weather by the kettle", "Polite nothings at the printer"],
  "assembly instructions": ["Step 14, and a spare screw", "Flat pack diagram with no words"],
  "airport security": ["Shoes off, laptop out", "Queue, tray, beeping archway"],
  "tax return": ["Yearly paperwork for the government", "Receipts, deadlines and a headache"],

  vibe: ["The whole feel of a place", "Not a fact, just an energy"],
  mood: ["A picture that is exactly how you feel", "Relatable enough to repost"],
  slay: ["Absolutely nailed the outfit", "Did it perfectly, made it look easy"],
  flex: ["Showing off the new trainers", "A humble brag, minus the humble"],
  drip: ["Fit so good people ask where it is from", "Top-tier style, head to toe"],
  ick: ["That instant turn-off feeling", "One habit ruins the whole crush"],
  bop: ["A song you replay instantly", "Absolute banger of a tune"],
  salty: ["Still bitter about losing", "Taking the loss very badly"],
  based: ["Saying what you think, no filter", "Unbothered by what people will say"],
  extra: ["Way over the top for no reason", "Always doing the most"],
  cringe: ["Makes you physically look away", "Second-hand embarrassment"],
  bussin: ["Food so good you tell everyone", "Genuinely delicious, no notes"],
  bet: ["Agreed, say no more", "A one-word yes"],
  sus: ["Something feels off about them", "Acting shady, worth watching"],
  tea: ["The juicy gossip", "Spill it — what happened?"],
  mid: ["Not bad, not good, just forgettable", "Painfully average"],
  ratio: ["When the reply beats the post", "More replies than likes, brutal"],
  bruh: ["The sound of pure disappointment", "One syllable that says really?"],
  "no cap": ["Swear it is the truth", "Not even exaggerating"],
  "side eye": ["The look you give when someone lies", "Judging without saying a word"],
  clout: ["Online influence you can cash in", "Fame, but make it internet"],
  rizz: ["Natural charm that wins people over", "Smooth talking, effortlessly"],
  ghosted: ["They stopped replying with no warning", "Vanished mid-conversation"],
  "glow up": ["A serious upgrade since school", "Came back looking completely different"],
  brainrot: ["What hours of short videos do to you", "Your feed melted your attention span"],
  doomscroll: ["Endless bad news before bed", "Cannot stop reading awful headlines"],
  "soft launch": ["Hinting at a romance without showing faces", "A blurry hand in your story"],
  "npc energy": ["Acting like a background game person", "Same three phrases on repeat"],
  delulu: ["Believing a fantasy way too hard", "Living in a dream you invented"],
  "red flag": ["A warning sign you should not ignore", "Time to walk away early"],
  "beige flag": ["A quirk that is neither good nor bad", "Mildly odd, totally harmless"],
  "side quest": ["A random detour from the main plan", "Unplanned adventure on the way home"],
  "touch grass": ["Advice to go outside for once", "Log off and breathe real air"],
  "main character": ["Acting like the world revolves around you", "Everyone else is just background"],
  situationship: ["Not dating, not not dating", "Undefined, and everyone knows it"],
  "caught in 4k": ["Busted on camera, no denying it", "Evidence in full resolution"],
};

export function bankCluesFor(word: string): string[] {
  return CLUE_BANK[word.toLowerCase().trim()] ?? [];
}

export const CLUE_BANK_WORD_COUNT = Object.keys(CLUE_BANK).length;
